### ISSUE TITLE
How to build properly?

### ISSUE THREAD

**Issue by fe-c** [PaoloW8/android_device_ZTE_NX505J#1]
Hello!
I do not understand how to properly build Yours firmware. I use your local configs and toolchain from Christopher83. After building the binary files are different and  Antutu provides 37,000 instead of 43,000 points, and no indicator of data transfer rate at the top.
Thank you very much for the excellent work!
# question

**Comment by PaoloW8** [comment]
strange, if you use my device and vendor tree AnTuTu should give 42-44k.
for the network transfer speed (and enable/disable root icon, enable/disable exlamation marks and enable/disable headset icon) I have patched the cyanogen sources so without those patches these features are missing

**Comment by fe-c** [comment]
With traffic indication is all clear, thanks. But with binary files I did not understand what was happening. Some files are identical, many different in one-two bytes, and some almost completely different, for example, libssl.so or libRScpp.so.

To build i use ubuntu-14.04.3-desktop-amd64 with all updates.
Repo inited with: repo init -u git://github.com/CyanogenMod/android.git -b cm-12.1
and local manifest like this:
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="CyanogenMod/android_device_qcom_common" path="device/qcom/common" remote="github" revision="cm-12.1" />
  <project name="CyanogenMod/android_hardware_qcom_fm" path="hardware/qcom/fm" remote="github" revision="cm-12.1" />
  <project name="Christopher83/arm-cortex_a15-linux-gnueabihf-linaro_4.9" path="prebuilts/gcc/linux-x86/arm/arm-cortex_a15-linux-gnueabihf-linaro_4.9" remote="github" revision="master" />
</manifest>
and other manifest with your device tree and vendor.
Environment setuped with android documentation. I'd love to understand what is wrong.

**Comment by fe-c** [comment]
All is clear, thank you. With  performance I will puzzle out. And where can I find out about that cyanogen source patches? Or is it an unique patches for this device?

**Comment by PaoloW8** [comment]
I got the patch for the network speed from Mokee source code https://github.com/MoKee
some other patch from prodoomman git https://gitlab.com/u/proDOOMman
and I made some other...I will publish in a few days

**Comment by fe-c** [comment]
Nice. Thank you so much.
